# Generated by Django 3.0.2 on 2020-02-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('conatct', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pasword', models.IntegerField()),
            ],
        ),
    ]
